### ISSUE TITLE
Advance to stage 1

### ISSUE THREAD

**Issue by benjamingr** [tc39-transfer/proposal-regex-escaping#2]
From [the tc39 process](https://docs.google.com/document/d/1QbEE0BsO4lvl7NFTn5WXWeiEIBfaVUF7Dk0hpPpPDzU/edit)
- [x] Identified “champion” who will advance the addition

This would be me, with the much appreciated help of @domenic . Others (Uri Shaked and Elad Kats) have offered help with the process.
- [x] Prose outlining the problem or need and the general shape of a solution

Done in the readme.
- [x] Illustrative examples of usage

Done in the readme.
- [x] High-level API

Done in the readme, including semantics and a polyfill and a spec to JS file. The semantics spec will likely be moved to ECMarkup format.
- [X] Discussion of key algorithms, abstractions and semantics

This is a relatively simple proposal - covered in https://github.com/benjamingr/RexExp.escape/issues/3 and https://github.com/benjamingr/RexExp.escape/issues/4. A template tag is still considered but as it looks from #4 it seems inferior.
- [X] Identification of potential “cross-cutting” concerns and implementation challenges/complexity.

Done, and updated the readme file to address these.
- [ ]  Get TC39 to agree that we have advanced to stage 1, after meeting all the above requirements.

**Comment by ljharb** [comment]
I've put up a polyfill at https://github.com/ljharb/regexp.escape and https://npmjs.com/regexp.escape, with tests, working in ES3. Once this is accepted as a stage 0 proposal I'll add it to the `es7-shim` and ES7 Compabilitity Table as well.

**Comment by benjamingr** [comment]
Just mentioning -  this has already been added to core.js.

The polyfill here should already work on ES3 by the way as far as I'm aware
(Only tested in one browser though), if you want to pick up publishing and
maintaining it that's awesome! Thanks!

**Comment by ljharb** [comment]
Your polyfill here uses arrow functions, `let`, `for..of`, `Array.from`, and `Symbol` (which is impossible to truly polyfill in ES5 or below).

In order to be included in the es7-shim, a polyfill needs to implement a `shim` method which installs it (correctly non-enumerably, with the right length and name) in the environment, not modify the environment by default, and be published such that it's directly consumable in ES3. It also needs to be robust in case someone modifies the global `Array.from` (you may want to use the spread operator instead), or `String.prototype.indexOf`, `Array.prototype.push`, `String`,  and `Array.prototype.join`. I'm definitely happy to maintain all of these concerns in my polyfill :-)

**Comment by benjamingr** [comment]
@ljharb oh thanks, I see the confusion. 

I have included two files: 

 - [polyfill.js](https://github.com/benjamingr/RexExp.escape/blob/master/polyfill.js) which is a polyfill
 - [specInJs.js](https://github.com/benjamingr/RexExp.escape/blob/master/specInJs.js) which is a direct translation of the spec language. 

Thanks for maintaining this and taking care of people trying it out - very helpful, be sure to let me know if you get any positive/negative feedback about it :)

**Comment by ljharb** [comment]
Ah, thanks, I'd missed that :-)

Will do! I think this is a great proposal and am excited to see it land.

**Comment by benjamingr** [comment]
@ljharb note that the polyfill changed a little (String coerce and not escape `/`) so you might want to update it.

**Comment by ljharb** [comment]
Thanks, all taken care of.

**Comment by ljharb** [comment]
We're at stage 1.
